services:
  adguardhome:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguardhome.rule=Host(`adguardhome.$DOMAINNAME`)"
      - "traefik.http.routers.adguardhome.entrypoints=https"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=3000"
    image: adguard/adguardhome
    container_name: adguardhome
    network_mode: host
    #networks:
    #  - containerProxy
    #ports:
    #  - "53:53/tcp"
    #  - "53:53/udp"
    #  - "67:67/udp"
    #  - "853:853/tcp"
    environment:
      TZ: $TZ
    volumes:
      - $CONTAINERDATADIR/adguardhome/work:/opt/adguardhome/work
      - $CONTAINERDATADIR/adguardhome/conf:/opt/adguardhome/conf
      - $CONTAINERDIR/logs/adguardhomeQueryLog.json:/opt/adguardhome/work/data/querylog.json
    dns:
      - 1.1.1.1
      - 1.0.0.1
    depends_on:
      - traefik
    restart: unless-stopped
