services:
  airsonic:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airsonic.rule=Host(`airsonic.$DOMAINNAME`)"
      - "traefik.http.routers.airsonic.entrypoints=https"
      - "traefik.http.services.airsonic.loadbalancer.server.port=4040"
    image: linuxserver/airsonic
    container_name: airsonic
    volumes:
      - $CONTAINERDATADIR/airsonic:/config
      - $DATADIR/Music:/music
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
    networks:
      - containerProxy
    restart: unless-stopped
