services:
  glances:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances.rule=Host(`glances.$DOMAINNAME`)"
      - "traefik.http.routers.glances.entrypoints=https"
      - "traefik.http.services.glances.loadbalancer.server.port=61208"
    image: vimagick/glances
    container_name: glances
    volumes:
      - $CONTAINERDATADIR/glances:/etc/glances
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w
    networks:
      - containerProxy
    pid: host
    depends_on:
      - traefik
    restart: unless-stopped
