services:
  jellyfin:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.$DOMAINNAME`)"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.middlewares=jellyfin"
      - "traefik.http.middlewares.jellyfin.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.jellyfin.headers.contentSecurityPolicy=frame-ancestors 'self' jellyfin.$DOMAINNAME"
      - "traefik.http.middlewares.jellyfin.headers.stsSeconds=155520011"
      - "traefik.http.middlewares.jellyfin.headers.stsPreload=true"
      - "traefik.http.middlewares.jellyfin.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.jellyfin.headers.browserXSSFilter=true"
    image: jellyfin/jellyfin
    container_name: jellyfin
    runtime: nvidia
    volumes:
      - $CONTAINERDATADIR/jellyfin:/config
      - $CONTAINERDATADIR/jellyfin/cache:/cache
      - $DATADIR:/data
      - /dev/shm:/dev/shm:rw
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: host
    depends_on:
      - traefik
    restart: unless-stopped
