services:
  mongodb:
    image: library/mongo
    container_name: mongodb
    command: ['--directoryperdb', '--config', '/data/db/mongod.conf']
    volumes:
      - $CONTAINERDATADIR/mongo:/data/db
      - $CONTAINERDIR/config/mongodb/mongod.conf:/data/db/mongod.conf
    networks:
      - containerProxy
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 5s
      timeout: 20s
      retries: 10
      start_period: 40s
    restart: unless-stopped
