services:
  radarr:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.$DOMAINNAME`)"
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    image: mdhiggins/radarr-sma:nightly
    container_name: radarr
    volumes:
      - $CONTAINERDATADIR/radarr:/config
      - $CONTAINERDIR/config/autoProcess.ini:/usr/local/sma/autoProcess.ini
      - $DATADIR:/data
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    devices:
      - /dev/dri:/dev/dri
    network_mode: container:wireguard
    depends_on:
      - traefik
      - nzbget
      - qbittorrent
      - jackett
      - nzbhydra
      - wireguard
    restart: unless-stopped
