services:
  rclone:
    image: rclone/rclone
    container_name: rclone
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /mnt/rclone:/mnt/rclone:shared
      - $CONTAINERDIR/config/rclone/rclone.conf:/config/rclone/rclone.conf
      - $CONTAINERDATADIR/rclone:/config/rclone
      - /mnt/cache/tmp:/tmp
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    network_mode: host
    restart: unless-stopped
    command: --allow-other --allow-non-empty --log-level INFO mount --dir-perms 0777 --file-perms 0777 --rc --rc-no-auth --use-mmap --write-back-cache --bwlimit 10M cache:/ /mnt/rclone
