services:
  scrutiny:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scrutiny.rule=Host(`scrutiny.$DOMAINNAME`)"
      - "traefik.http.routers.scrutiny.entrypoints=https"
      - "traefik.http.services.scrutiny.loadbalancer.server.port=8080"
      - "ofelia.enabled=true"
      - "ofelia.job-exec.scrutiny-metrics.schedule=@every 10m"
      - "ofelia.job-exec.scrutiny-metrics.command=scrutiny-collector-metrics run"
    image: ghcr.io/linuxserver/scrutiny
    container_name: scrutiny
    volumes:
      - $CONTAINERDATADIR/scrutiny:/config
      - /run/udev:/run/udev:ro
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - SCRUTINY_API_ENDPOINT=http://localhost:8080
      - SCRUTINY_WEB=true
      - SCRUTINY_COLLECTOR=true
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
      - /dev/sdf:/dev/sdf
      - /dev/sdg:/dev/sdg
      - /dev/sdh:/dev/sdh
      - /dev/nvme0:/dev/nvme0
      - /dev/nvme1:/dev/nvme1
    networks:
      - internet
    depends_on:
      - traefik
      - ofelia
    restart: unless-stopped
