services:
  tvheadend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tvheadend.rule=Host(`tvh.$DOMAINNAME`)"
      - "traefik.http.routers.tvheadend.entrypoints=https"
      - "traefik.http.services.tvheadend.loadbalancer.server.port=9981"
    image: ghcr.io/linuxserver/tvheadend
    container_name: tvheadend
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONTAINERDATADIR/tvheadend:/config
      - $DATADIR/recordings:/recordings
    network_mode: host
    depends_on:
      - traefik
      - oscam
    restart: unless-stopped

  oscam:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oscam.rule=Host(`oscam.$DOMAINNAME`)"
      - "traefik.http.routers.oscam.entrypoints=https"
      - "traefik.http.services.oscam.loadbalancer.server.port=8888"
    image: ghcr.io/linuxserver/oscam
    container_name: oscam
    environment:
      - PUID=$PUID
      - GUID=$GUID
      - TZ=$TZ
    volumes:
      - $CONTAINERDATADIR/oscam:/config
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    network_mode: host
    depends_on:
      - traefik
    restart: unless-stopped
